version: "3"
services:
  react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /usr/apps/node-app/node_modules
      - .:/usr/apps/node-app
  test-react-app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /usr/apps/node-app/node_modules
      - .:/usr/apps/node-app
    
    command: ["npm", "run", "test"]
  